# Generated by Django 5.1.6 on 2025-02-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_payments', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
